aprs:
  callsign: 'UR5WKM-10'
  host: "rotate.aprs2.net"
  filter: "s/O"
  ignore_comment:
    - "RS41"
    - "auto_rx"
    - "Radiosonde"
    - "SondeID"
    - "NSM is Not Sonde Monitor"
    - "ZOE APRS EV ZERO-EMMISSION"
  ignore_call_sign:
    - "PC4L-15"
    - "PC4L-13"
    - "WIDE3-3"
    - "WIDE3-2"
    - "WIDE3-1"
    - "WIDE2-2"
    - "WIDE2-1"
    - "WIDE1-1"

history:
  # Allowed any number or string 'all' to keep all results in db
  keep: 'all'

logging:
  # Allowed levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: 'INFO'

mysql:
  hostname: 'localhost'
  unix_socket: '/run/mysqld/mysqld.sock'
  username: 'root'
  password: 'a'
  database: 'hab_tracker'